import fs from "fs";
import path from "path";
import { config } from "@/lib/config";

/**
 * Build logs on disk, one file per deployment.
 *
 * They used to live in a TEXT column, appended one line at a time with
 * `build_log = build_log || ?`. That rewrites the entire column on every line,
 * so a build producing a few thousand lines — an ordinary Docker build does —
 * costs quadratic work and grows the database with output nobody queries.
 *
 * A file also gives cheap tailing, which is what the log viewer wants on first
 * paint before it switches to the live stream.
 */

export function buildLogDir(): string {
  return path.join(config.logsDir, "deployments");
}

export function buildLogPath(deploymentId: string): string {
  // Deployment ids are nanoids generated by us, but this is a filesystem path:
  // refuse anything that is not the shape we generate.
  if (!/^[A-Za-z0-9_-]{1,32}$/.test(deploymentId)) {
    throw new Error(`Invalid deployment id: ${deploymentId}`);
  }
  return path.join(buildLogDir(), `${deploymentId}.log`);
}

/**
 * An append stream for one deployment.
 *
 * Writes are buffered and flushed on a timer so a chatty build does not do one
 * syscall per line, and every line is still on disk shortly after it happens.
 */
export class BuildLogFile {
  private pending: string[] = [];
  private timer: NodeJS.Timeout | null = null;
  private readonly file: string;

  constructor(deploymentId: string, private readonly flushMs = 200) {
    this.file = buildLogPath(deploymentId);
    fs.mkdirSync(path.dirname(this.file), { recursive: true });
  }

  append(line: string): void {
    this.pending.push(line);
    if (this.timer) return;
    this.timer = setTimeout(() => {
      this.timer = null;
      this.flush();
    }, this.flushMs);
  }

  flush(): void {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
    if (this.pending.length === 0) return;

    const chunk = `${this.pending.join("\n")}\n`;
    this.pending = [];
    try {
      fs.appendFileSync(this.file, chunk);
    } catch (err) {
      console.error("[build-log] Failed to write:", err);
    }
  }
}

/** Read a deployment's log. `tailLines` returns only the end of it. */
export function readBuildLog(deploymentId: string, tailLines?: number): string {
  let file: string;
  try {
    file = buildLogPath(deploymentId);
  } catch {
    return "";
  }

  if (!fs.existsSync(file)) return "";

  try {
    const content = fs.readFileSync(file, "utf8");
    if (!tailLines) return content;

    const lines = content.split("\n");
    return lines.slice(Math.max(0, lines.length - tailLines)).join("\n");
  } catch {
    return "";
  }
}

export function removeBuildLog(deploymentId: string): void {
  try {
    const file = buildLogPath(deploymentId);
    if (fs.existsSync(file)) fs.rmSync(file, { force: true });
  } catch {
    /* an unparseable id has no file to remove */
  }
}

/** Drop logs for deployments that no longer exist. */
export function pruneBuildLogs(keepDeploymentIds: Set<string>): number {
  const dir = buildLogDir();
  if (!fs.existsSync(dir)) return 0;

  let removed = 0;
  for (const entry of fs.readdirSync(dir)) {
    if (!entry.endsWith(".log")) continue;
    const id = entry.slice(0, -4);
    if (keepDeploymentIds.has(id)) continue;
    try {
      fs.rmSync(path.join(dir, entry), { force: true });
      removed++;
    } catch {
      /* keep going — one stuck file should not stop the sweep */
    }
  }
  return removed;
}
