import path from "path";
import { config } from "@/lib/config";
import {
  AppendLogFile,
  logPathFor,
  pruneLogDir,
  readLogFile,
} from "./log-file";

/**
 * Build logs on disk, one file per deployment.
 *
 * They used to live in a TEXT column, appended one line at a time with
 * `build_log = build_log || ?`. That rewrites the entire column on every line,
 * so a build producing a few thousand lines — an ordinary Docker build does —
 * costs quadratic work and grows the database with output nobody queries.
 *
 * A file also gives cheap tailing, which is what the log viewer wants on first
 * paint before it switches to the live stream.
 *
 * The mechanics live in `log-file.ts`; what stays here is the deployment
 * naming, so a caller never has to know where a build log is kept.
 */

export function buildLogDir(): string {
  return path.join(config.logsDir, "deployments");
}

export function buildLogPath(deploymentId: string): string {
  // Deployment ids are nanoids generated by us, but this is a filesystem path:
  // refuse anything that is not the shape we generate.
  return logPathFor(buildLogDir(), deploymentId);
}

export class BuildLogFile extends AppendLogFile {
  constructor(deploymentId: string, flushMs = 200) {
    super(buildLogPath(deploymentId), flushMs);
  }
}

/** Read a deployment's log. `tailLines` returns only the end of it. */
export function readBuildLog(deploymentId: string, tailLines?: number): string {
  try {
    return readLogFile(buildLogPath(deploymentId), tailLines);
  } catch {
    return "";
  }
}


/** Drop logs for deployments that no longer exist. */
export function pruneBuildLogs(keepDeploymentIds: Set<string>): number {
  return pruneLogDir(buildLogDir(), keepDeploymentIds);
}
