import fs from "fs";
import path from "path";
import { config } from "@/lib/config";
import { resolveInside } from "@/lib/fs-safe";

/**
 * Writes a project's environment out as a real `.env` file.
 *
 * Needed because some applications read a dotenv file themselves rather than
 * trusting `process.env`. Docker's own `--env-file` is not an alternative: its
 * parser does not strip surrounding quotes, so `KEY="value"` arrives as
 * `"value"` including the quote characters — which silently corrupts connection
 * strings and proxy URLs.
 *
 * The file contains every secret the project has, so it is written 0600 and
 * mounted read-only.
 */

export function envFileDir(): string {
  return path.join(config.dataDir, "envs");
}

export function envFilePath(slug: string): string {
  return path.join(envFileDir(), `${slug}.env`);
}

/**
 * Quote a value only when it needs it, and escape what would otherwise end the
 * quoted run. Values containing newlines are the common trap: a raw newline
 * turns one variable into two.
 */
function serialize(key: string, value: string): string {
  const needsQuotes = /[\s"'#$`\\]|^$/.test(value);
  if (!needsQuotes) return `${key}=${value}`;

  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");

  return `${key}="${escaped}"`;
}

/** Write the file and return its path on the host. */
export function writeEnvFile(slug: string, envVars: Record<string, string>): string {
  const dir = envFileDir();
  fs.mkdirSync(dir, { recursive: true });

  const target = envFilePath(slug);
  const body =
    "# Generated by RunPanel. Edits here are overwritten on the next deploy.\n" +
    Object.entries(envVars)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, value]) => serialize(key, value))
      .join("\n") +
    "\n";

  fs.writeFileSync(target, body, { mode: 0o600 });
  // writeFileSync only applies the mode when creating, so enforce it on rewrite.
  try {
    fs.chmodSync(target, 0o600);
  } catch {
    /* chmod is a no-op on some Windows filesystems */
  }

  return target;
}

export function removeEnvFile(slug: string): void {
  const target = envFilePath(slug);
  if (fs.existsSync(target)) fs.rmSync(target, { force: true });
}

/**
 * For native runtimes there is nothing to mount — the app reads a file from its
 * own working directory, so put one there.
 */
export function writeEnvFileInto(repoDir: string, relativePath: string, envVars: Record<string, string>): string {
  // Never let a configured path escape the project directory. This wrote every
  // one of the project's decrypted variables, and the check used to be a bare
  // `startsWith`, which accepts `../app-x/.env` next to a project called `app`.
  const target = resolveInside(repoDir, relativePath);
  if (!target) {
    throw new Error(`envFile.path esce dalla directory del progetto: ${relativePath}`);
  }

  fs.mkdirSync(path.dirname(target), { recursive: true });
  const body = Object.entries(envVars)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => serialize(key, value))
    .join("\n");

  fs.writeFileSync(target, `${body}\n`, { mode: 0o600 });
  return target;
}
