/**
 * The files that make RunPanel come back after a reboot.
 *
 * Pure functions with no imports at all, which is what lets the unit suite
 * check them on any machine — no Linux, no root, no daemon. Everything they
 * need is passed in, because "what this host looks like" is a probe's job and
 * "what the unit should say" is this one's.
 */

export interface UnitInput {
  /** Absolute path to the node binary running the panel. */
  nodePath: string;
  /** Absolute path to next's own bin script. */
  nextBin: string;
  workingDirectory: string;
  user: string;
  group?: string;
  port: number;
  dataDir: string;
  /** `.env` beside the working directory; a missing one must not fail the boot. */
  envFile: string;
}

export const UNIT_NAME = "runpanel.service";
export const UNIT_PATH = `/etc/systemd/system/${UNIT_NAME}`;

/**
 * The systemd unit.
 *
 * Decisions worth knowing about:
 *
 *  - **absolute paths**, never `npm start`. npm would sit between systemd and
 *    the server as PID 1's child, and signals would stop reaching the process
 *    that has to handle them.
 *  - **`Requires=docker.service`**, not merely `After=`. Every feature of the
 *    panel needs Docker; one that boots without it is a support ticket, not a
 *    degraded mode.
 *  - **`EnvironmentFile=-`** with the leading dash, so a host with no `.env`
 *    still boots.
 *  - **no `RUNPANEL_SECRET`**. It stays in `.env` or `data/.secret`, both 0600.
 *    A unit file is world-readable, and the key in it decrypts every stored
 *    credential — that would undo everything `lib/config.ts` is careful about.
 *  - **`ProtectHome=no`**, because `~/.pm2` and the Docker socket have to stay
 *    reachable, and `KillSignal=SIGINT` so `next start` shuts down cleanly.
 */
export function renderUnit(input: UnitInput): string {
  const lines = [
    "[Unit]",
    "Description=RunPanel",
    "Documentation=https://github.com/AlessTRV/RunPanel",
    "After=network-online.target docker.service",
    "Wants=network-online.target",
    "Requires=docker.service",
    "",
    "[Service]",
    "Type=simple",
    `User=${input.user}`,
    ...(input.group ? [`Group=${input.group}`] : []),
    `WorkingDirectory=${input.workingDirectory}`,
    `EnvironmentFile=-${input.envFile}`,
    "Environment=NODE_ENV=production",
    `Environment=PORT=${input.port}`,
    `Environment=RUNPANEL_DATA_DIR=${input.dataDir}`,
    `ExecStart=${input.nodePath} ${input.nextBin} start -p ${input.port}`,
    "Restart=always",
    "RestartSec=5",
    "TimeoutStopSec=30",
    "KillSignal=SIGINT",
    "StandardOutput=journal",
    "StandardError=journal",
    "NoNewPrivileges=yes",
    "ProtectSystem=full",
    "ProtectHome=no",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ];
  return lines.join("\n");
}

/**
 * The cron path writes a script and points `@reboot` at it.
 *
 * A pipeline inside a crontab line is unreadable, impossible to quote reliably
 * and impossible to fix by hand. A script can be inspected, and the panel can
 * rewrite it without touching the crontab at all.
 *
 * It also supervises: cron has no `Restart=`, so without the loop a crash on a
 * cron-managed host means the panel is gone until someone notices.
 */
export function renderStartScript(input: UnitInput, logFile: string): string {
  return [
    "#!/bin/sh",
    "# Generated by RunPanel. Edit the schedule from the Autostart page, not here.",
    "set -u",
    `cd ${shellQuote(input.workingDirectory)} || exit 1`,
    `[ -f ${shellQuote(input.envFile)} ] && . ${shellQuote(input.envFile)}`,
    "export NODE_ENV=production",
    `export PORT=${input.port}`,
    `export RUNPANEL_DATA_DIR=${shellQuote(input.dataDir)}`,
    "",
    "# cron has no Restart=, so supervise the process here instead.",
    "while true; do",
    `  ${shellQuote(input.nodePath)} ${shellQuote(input.nextBin)} start -p ${input.port} >> ${shellQuote(logFile)} 2>&1`,
    `  echo "[runpanel] uscito con codice $?, riavvio tra 5s" >> ${shellQuote(logFile)}`,
    "  sleep 5",
    "done",
    "",
  ].join("\n");
}

export function crontabLine(scriptPath: string): string {
  return `@reboot ${scriptPath}`;
}

/** Single-quote for /bin/sh, closing and reopening around any quote inside. */
export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * The commands to run by hand when the panel is not root.
 *
 * A heredoc rather than "open an editor and paste this": one paste, nothing to
 * get wrong, and the unit that lands is byte-for-byte the one the panel would
 * have written itself.
 */
export function installCommands(unit: string): string[] {
  return [
    `sudo tee ${UNIT_PATH} > /dev/null <<'RUNPANEL_EOF'\n${unit}RUNPANEL_EOF`,
    "sudo systemctl daemon-reload",
    `sudo systemctl enable ${UNIT_NAME}`,
  ];
}

export function uninstallCommands(): string[] {
  return [
    `sudo systemctl disable ${UNIT_NAME}`,
    `sudo rm -f ${UNIT_PATH}`,
    "sudo systemctl daemon-reload",
  ];
}
