/**
 * Generates lib/icons.generated.ts: the Iconify data for exactly the icons this
 * codebase references, and nothing else.
 *
 * Why this exists: @iconify/react fetches icon data from api.iconify.design at
 * runtime. A self-hosted panel on a private network — which is the whole point
 * of RunPanel — would render no icons at all. Bundling the alternative is not
 * an option either: @iconify-json/solar is 6.2 MB across 7404 icons and JSON
 * cannot be tree-shaken.
 *
 * Run after adding or renaming an icon:  npm run icons
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, extname } from "node:path";

const ROOT = process.cwd();
const SOURCE_DIRS = ["app", "components", "lib"];
const ICON_RE = /["'`](solar:[a-z0-9-]+)["'`]/g;

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, out);
    } else if ([".ts", ".tsx"].includes(extname(entry))) {
      out.push(full);
    }
  }
  return out;
}

const used = new Set();
for (const dir of SOURCE_DIRS) {
  let files;
  try {
    files = walk(join(ROOT, dir));
  } catch {
    continue;
  }
  for (const file of files) {
    const text = readFileSync(file, "utf8");
    for (const match of text.matchAll(ICON_RE)) used.add(match[1]);
  }
}

const names = [...used].sort();
if (names.length === 0) {
  console.warn("[icons] No solar:* icon references found — nothing to generate.");
}

const collection = JSON.parse(
  readFileSync(join(ROOT, "node_modules/@iconify-json/solar/icons.json"), "utf8")
);

const icons = {};
const missing = [];
for (const name of names) {
  const key = name.slice("solar:".length);
  const data = collection.icons[key] ?? collection.aliases?.[key];
  if (!data) {
    missing.push(name);
    continue;
  }
  // Resolve one level of alias so the runtime never needs the alias table.
  icons[key] = data.parent ? { ...collection.icons[data.parent], ...data } : data;
  delete icons[key].parent;
}

if (missing.length > 0) {
  console.error(`[icons] Unknown icon names (typo?):\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const payload = {
  prefix: collection.prefix,
  width: collection.width,
  height: collection.height,
  icons,
};

const output = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Regenerate with: npm run icons
import type { IconifyJSON } from "@iconify/types";

/** ${names.length} icons, extracted from @iconify-json/solar. */
export const solarSubset = ${JSON.stringify(payload, null, 2)} as unknown as IconifyJSON;
`;

writeFileSync(join(ROOT, "lib/icons.generated.ts"), output);

const bytes = Buffer.byteLength(output);
console.log(
  `[icons] Wrote lib/icons.generated.ts — ${names.length} icons, ${(bytes / 1024).toFixed(1)} KB`
);
